---
AWSTemplateFormatVersion: 2010-09-09
Description: Amazon EKS - Node Group

Parameters:
  ClusterName:
    Description: The cluster name provided when the cluster was created. If it is incorrect, nodes will not be able to join the cluster.
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: EKS Cluster
        Parameters:
          - ClusterName

Resources:
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties: 
      Name: !Ref ClusterName
      ResourcesVpcConfig: 
        SecurityGroupIds: 
        - Fn::ImportValue:
            !Join [ ':', [ 'VPCEKSStack', 'ControlPlaneSecurityGroup' ] ]     
        SubnetIds: 
          - Fn::ImportValue:
              !Join [ ':', [ 'VPCEKSStack', 'PrivateSubnet01' ] ] 
          - Fn::ImportValue:
              !Join [ ':', [ 'VPCEKSStack', 'PrivateSubnet02' ] ] 
      RoleArn: !GetAtt EKSClusterRole.Arn
      Version: 1.17

Outputs:

  EKSClusterName:
    Description: EKS cluster name
    Value: !Ref EKSCluster
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'EksClusterName' ] ]

